import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{api,onTwitchAuth,TwitchAuth}from'./twitch';
function Broadcaster(){const[auth,setAuth]=useState<TwitchAuth>();const[data,setData]=useState<any>();const[season,setSeason]=useState('Saison 1');const[stamp,setStamp]=useState({title:'Tampon spécial',imageUrl:'/stamps/custom.svg',kind:'custom',activate:true});const[reward,setReward]=useState({title:'VIP du passeport',description:'Récompense à donner manuellement ou via Discord.',requiredStamps:10});async function load(a=auth){if(a)setData(await api('/api/admin',a))}useEffect(()=>onTwitchAuth(async a=>{setAuth(a);await load(a)}),[]);async function post(path:string,body:any){if(!auth)return;await api(path,auth,{method:'POST',body:JSON.stringify(body)});await load(auth)}return <div className="wrap"><main className="passport"><section className="cover"><h1>ADMIN PASSEPORT</h1><div>{data?.season?.name}</div></section><section className="page">
<h2>Saison</h2><div className="form"><label>Nom saison</label><input value={season} onChange={e=>setSeason(e.target.value)}/><button className="btn" onClick={()=>post('/api/admin/season',{name:season})}>Créer/activer saison</button></div>
<h2>Tampon custom</h2><div className="form"><input placeholder="Titre" value={stamp.title} onChange={e=>setStamp({...stamp,title:e.target.value})}/><input placeholder="URL image SVG/PNG" value={stamp.imageUrl} onChange={e=>setStamp({...stamp,imageUrl:e.target.value})}/><select value={stamp.kind} onChange={e=>setStamp({...stamp,kind:e.target.value})}><option value="custom">Custom</option><option value="daily">Quotidien</option><option value="event">Événement</option></select><label><input type="checkbox" checked={stamp.activate} onChange={e=>setStamp({...stamp,activate:e.target.checked})}/> Actif pour le live du jour</label><button className="btn" onClick={()=>post('/api/admin/stamps',stamp)}>Créer tampon</button></div>
<h2>Récompense</h2><div className="form"><input value={reward.title} onChange={e=>setReward({...reward,title:e.target.value})}/><textarea value={reward.description} onChange={e=>setReward({...reward,description:e.target.value})}/><input type="number" value={reward.requiredStamps} onChange={e=>setReward({...reward,requiredStamps:+e.target.value})}/><button className="btn" onClick={()=>post('/api/admin/rewards',reward)}>Créer récompense</button></div>
<h2>Tampons</h2><table><tbody>{data?.stamps?.map((s:any)=><tr key={s.id}><td>{s.isActive?'🟢':'⚪'}</td><td>{s.title}</td><td>{s.kind}</td></tr>)}</tbody></table>
<h2>Récompenses</h2><table><tbody>{data?.rewards?.map((r:any)=><tr key={r.id}><td>{r.requiredStamps}</td><td>{r.title}</td><td>{r.description}</td></tr>)}</tbody></table>
</section></main></div>}
createRoot(document.getElementById('root')!).render(<Broadcaster/>);
